name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package

      - name: Archive JAR
        uses: actions/upload-artifact@v2
        with:
          name: application-jar
          path: target/*.jar


