name: Feature Branch CI
on:
  push:
    branches:
      - feature/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-java
        with:
          java-version: 20
          distribution: temurin
      - run: mvn test--filepom.xml
